### ISSUE TITLE
Language specification

### ISSUE THREAD

**Issue by fmorgner** [morgner/te#1]
There currently is no formal specification of the template language. This makes it hard for beginners to know how the language works. Additionally, I personally encountered issues during test development that resultet from the current implementation having counterintuitive syntax/semantics.

I propose to formalize the template language into some generic notation, for example EBNF. Additionally, there should be a specification of the semantics as well.

**Comment by morgner** [comment]
Work in progress

**Comment by morgner** [comment]
Language is described, see te-LANGSPEC.md
