### ISSUE TITLE
Rename TMapS2M to something more meaningful

### ISSUE THREAD

**Issue by fmorgner** [morgner/te#2]
Currently, all template context is provided via objects of type `TMapS2M`. While the name is reflective of the nature of the type, it unnecessarily exposes the implementation details of being a 'Map of strings to multimaps'. User should not be exposed to the concrete implementation details, but rather to the abstract concepts.

Since objects of type `TMapS2M` are essentially used to provide an instantiation context for the templates, I would suggest to change its name to something like `Context`. This makes the purpose of the type clear while at the same time hiding the underlying nature of the type, thus providing better abstraction.

**Comment by morgner** [comment]
Renamed to TRenderData
