### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by fmorgner** [morgner/te#3]
The current implementation of the instantiation mechanism drops placeholders that have not been found entirely. This makes it hard to debug instantiation problem due to missing values.

I feel that it would be more appropriate to leave the placeholders intact in case no valid replacement has been found. This would allow users to easily detect that the value for the given context element is missing.

**Comment by morgner** [comment]
After interpreting the template no data tag must be left over. 

But some error output in debug mode will be provided (not complete yet)

**Comment by morgner** [comment]
solved, error will be send to std::cerr in DEBUG mode
