### ISSUE TITLE
For loop syntax/semantics

### ISSUE THREAD

**Issue by fmorgner** [morgner/te#4]
I find the current implementation of 'for loops' to be counter intuitive. From what I understand, they currently work like this:

**Context:**
```c++
auto ctx = TMapS2M{
    {"variable", {{"", "value1"}}},
    {"variable", {{"", "value2"}}},
};
```

**Template:**
```text
{% for variable in x %}{{ variable }}{% endfor %}
```

**Result:**
```text
value1value2
```

This raises the following questions:
  - What is `x` and why is it needed?
  - Why can't we reference `x`?

I would suggest that, regardless of the current implementation, the following usage/behavior would be more intuitive (note that I replaced `TMapS2M` with `Context` since we currently can't reflect the desired behaviour):

**Context:**
```c++
auto ctx = Context{            // A context is some abstract form of template context
    {
        "some_list", List{     // lists are composites of unnamed objects
            {{"", "value1"}},  // objects are maps of strings to strings
            {{"", "value2"}},
        },
    }
};
```

**Template:**
```text
{% for obj in some_list %}{{ obj }}{% endfor %}
```

**Result:**
```text
value1value2
```

This would reflect the 'for-each' semantic of common programming languages while also logically grouping objects into lists.

**Comment by morgner** [comment]
What is x and why is it needed?

At the moment x is a dummy element and only necessary to build the necessary pattern to recognize a loop. It is planned to enhance te so x becomes of practical use. Currently, the render-data structure is not fit for this.

Why can't we reference x?

There is nothings associated with x besides the template element pattern interpreter. This will be solved later.

**Comment by morgner** [comment]
It is now explained in the template language spcification te-LANGSPEC.md

The issue will be held open until solved, but may change its nature to a task.

**Comment by morgner** [comment]
Moved to Kanban board of project te.
